## **PROJECT: PART B**
Using web scraping to build a database of movie related information
from: The Movie Database (TMDB) movie data

1. Establish a connection to the webpage - "https://www.themoviedb.org/movie" - and provide the following
details

1.a. Import the requests library (https://requests.readthedocs.io/en/latest/ ) and formulate a
get request to download the contents of the webpage
( "https://www.themoviedb.org/movie" )

In [ ]:
import requests
needed_headers = {'User-Agent': "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36",'Accept-Language': 'en'}
url = "https://www.themoviedb.org/movie"
response = requests.get(url,headers = needed_headers)

1.b. Verify the status code of the request and confirm that the request was executed
appropriately (https://requests.readthedocs.io/en/latest/user/quickstart/#response
status-code)

In [ ]:
response.status_code
if response.status_code == 200:
    print("Request was successful")
else:
    print("Request failed with status code:", response.status_code)

Request was successful

1.c. Print the contents of the page obtained from the response and save it in a variable
(https://requests.readthedocs.io/en/latest/user/quickstart/#response-content)

In [ ]:
page_content = response.text
print(page_content)

<!DOCTYPE html>
<html lang="en" class="no-js">
  <head>
    <title>Popular Movies &#8212; The Movie Database (TMDB)</title>
    <meta http-equiv="cleartype" content="on">
    <meta charset="utf-8">
    <meta name="keywords" content="Movies, TV Shows, Streaming, Reviews, API, Actors, Actresses, Photos, User Ratings, Synopsis, Trailers, Teasers, Credits, Cast">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="viewport" content="width=device-width,initial-scale=1">
      <meta name="description" content="The Movie Database (TMDB) is a popular, user editable database for movies and TV shows.">
    <meta name="msapplication-TileImage" content="/assets/2/v4/icons/mstile-144x144-30e7905a8315a080978ad6aeb71c69222b72c2f75d26dab1224173a96fecc962.png">
<meta name="msapplication-TileColor" content="#032541">
<meta name="theme-color" content="#032541">
<link rel="apple-touch-icon" sizes="180x180" href="/assets/2/apple-touch-icon-57ed4b3b0450fd5e9a0c20f34e814b82adaa1085c79bdde2f00ca8787b63d2c4.png">
<link rel="icon" type="image/png" sizes="32x32" href="/assets/2/favicon-32x32-543a21832c8931d3494a68881f6afcafc58e96c5d324345377f3197a37b367b5.png">
<link rel="icon" type="image/png" sizes="16x16" href="/assets/2/favicon-16x16-b362d267873ce9c5a39f686a11fe67fec2a72ed25fa8396c11b71aa43c938b11.png">
<link rel="manifest" href="/manifest.json?version=3">
    <link rel="canonical" href="https://www.themoviedb.org/movie">
    <link rel="search" type="application/opensearchdescription+xml" title="TMDB Search" href="/opensearch.xml">
    <link rel="preload" href="/assets/2/Consensus-3cba2c4d050ea63dbf7783173d288faf9ecb2942515a5e7f6e1beecabb2eaf72.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="/assets/2/source-sans-pro-v14-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-regular-f38472b9e378b8c936f55a92677f575ab69e414d7cc3706ecfefeacd994b7975.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="/assets/2/source-sans-pro-v14-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-italic-48273a74acbc1611b6ef1d0a771bb8ef042b9922b51d5bff560571dddcb5542a.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="/assets/2/source-sans-pro-v14-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-300-db9f15a13a9f8b8bc46db7756ab863e8834bd20a7a1124c4c0a5a8f7892f3e99.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="/assets/2/source-sans-pro-v14-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-600-6a087a74d78fc7d7b97fa1b0911c4ff3be4ff0bd5144618fd7ddc63ef1777f3a.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="/assets/2/source-sans-pro-v14-vietnamese_latin-ext_latin_greek-ext_greek_cyrillic-ext_cyrillic-700-d67f7dff97d105f4ac5616b00fc7822ce2c33f653ece2f547995e6a71bb7b993.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="stylesheet" href="/assets/2/v4/fonts-dcbded27193f5556450c516bf4b553e851bc6d1c8d1c8e6da45a57e3fc278cff.css" media="screen">
    <link rel="stylesheet" href="/assets/2/application-6f8fac3fb42c8f97248a06d21a821ae926df35a7a4319bda760a8fd95e36dd59.css" media="screen">

      <link rel="stylesheet" href="/assets/2/v4/media-d65a112740c7f410033fc1a950402d9cf9753aad44666b98c63db5a6fe7b5416.css" media="screen">

      <link rel="stylesheet" href="/assets/2/v4/discover-b2c3bb76e3d2b2323e842dc4be56a342c51e08c3bb91c6a010e8b401b180f117.css" media="screen">

      <link rel="stylesheet" href="/assets/2/v4/account-cce66521478d16895d1c5e31e821f696433bada2fdee3fc3f9876fac529aa3c7.css" media="screen">

    <link rel="alternate" hreflang="x-default" href="https://www.themoviedb.org/movie">
    <link rel="alternate" hreflang="af-ZA" href="https://www.themoviedb.org/movie?language=af-ZA">
    <link rel="alternate" hreflang="ar-SA" href="https://www.themoviedb.org/movie?language=ar-SA">
    <link rel="alternate" hreflang="be-BY" href="https://www.themoviedb.org/movie?language=be-BY">
    <link rel="alternate" hreflang="bg-BG" href="https://www.themoviedb.org/movie?language=bg-BG">
    <link rel="alternate" hreflang="bn-BD" href="https://www.themoviedb.org/movie?language=bn-BD">
    <link rel="alternate" hreflang="br-FR" href="https://www.themoviedb.org/movie?language=br-FR">
    <link rel="alternate" hreflang="ca-ES" href="https://www.themoviedb.org/movie?language=ca-ES">
    <link rel="alternate" hreflang="ch-GU" href="https://www.themoviedb.org/movie?language=ch-GU">
    <link rel="alternate" hreflang="cs-CZ" href="https://www.themoviedb.org/movie?language=cs-CZ">
    <link rel="alternate" hreflang="cy-GB" href="https://www.themoviedb.org/movie?language=cy-GB">
    <link rel="alternate" hreflang="da-DK" href="https://www.themoviedb.org/movie?language=da-DK">
    <link rel="alternate" hreflang="de-DE" href="https://www.themoviedb.org/movie?language=de-DE">
    <link rel="alternate" hreflang="el-GR" href="https://www.themoviedb.org/movie?language=el-GR">
    <link rel="alternate" hreflang="en-US" href="https://www.themoviedb.org/movie?language=en-US">
    <link rel="alternate" hreflang="eo-EO" href="https://www.themoviedb.org/movie?language=eo-EO">
    <link rel="alternate" hreflang="es-ES" href="https://www.themoviedb.org/movie?language=es-ES">
    <link rel="alternate" hreflang="et-EE" href="https://www.themoviedb.org/movie?language=et-EE">
    <link rel="alternate" hreflang="eu-ES" href="https://www.themoviedb.org/movie?language=eu-ES">
    <link rel="alternate" hreflang="fa-IR" href="https://www.themoviedb.org/movie?language=fa-IR">
    <link rel="alternate" hreflang="fi-FI" href="https://www.themoviedb.org/movie?language=fi-FI">
    <link rel="alternate" hreflang="fr-FR" href="https://www.themoviedb.org/movie?language=fr-FR">
    <link rel="alternate" hreflang="ga-IE" href="https://www.themoviedb.org/movie?language=ga-IE">
    <link rel="alternate" hreflang="gd-GB" href="https://www.themoviedb.org/movie?language=gd-GB">
    <link rel="alternate" hreflang="gl-ES" href="https://www.themoviedb.org/movie?language=gl-ES">
    <link rel="alternate" hreflang="he-IL" href="https://www.themoviedb.org/movie?language=he-IL">
    <link rel="alternate" hreflang="hi-IN" href="https://www.themoviedb.org/movie?language=hi-IN">
    <link rel="alternate" hreflang="hr-HR" href="https://www.themoviedb.org/movie?language=hr-HR">
    <link rel="alternate" hreflang="hu-HU" href="https://www.themoviedb.org/movie?language=hu-HU">
    <link rel="alternate" hreflang="id-ID" href="https://www.themoviedb.org/movie?language=id-ID">
    <link rel="alternate" hreflang="it-IT" href="https://www.themoviedb.org/movie?language=it-IT">
    <link rel="alternate" hreflang="ja-JP" href="https://www.themoviedb.org/movie?language=ja-JP">
    <link rel="alternate" hreflang="ka-GE" href="https://www.themoviedb.org/movie?language=ka-GE">
    <link rel="alternate" hreflang="kk-KZ" href="https://www.themoviedb.org/movie?language=kk-KZ">
    <link rel="alternate" hreflang="kn-IN" href="https://www.themoviedb.org/movie?language=kn-IN">
    <link rel="alternate" hreflang="ko-KR" href="https://www.themoviedb.org/movie?language=ko-KR">
    <link rel="alternate" hreflang="ku-TR" href="https://www.themoviedb.org/movie?language=ku-TR">
    <link rel="alternate" hreflang="ky-KG" href="https://www.themoviedb.org/movie?language=ky-KG">
    <link rel="alternate" hreflang="lt-LT" href="https://www.themoviedb.org/movie?language=lt-LT">
    <link rel="alternate" hreflang="lv-LV" href="https://www.themoviedb.org/movie?language=lv-LV">
    <link rel="alternate" hreflang="ml-IN" href="https://www.themoviedb.org/movie?language=ml-IN">
    <link rel="alternate" hreflang="mr-IN" href="https://www.themoviedb.org/movie?language=mr-IN">
    <link rel="alternate" hreflang="ms-MY" href="https://www.themoviedb.org/movie?language=ms-MY">
    <link rel="alternate" hreflang="nb-NO" href="https://www.themoviedb.org/movie?language=nb-NO">
    <link rel="alternate" hreflang="nl-NL" href="https://www.themoviedb.org/movie?language=nl-NL">
    <link rel="alternate" hreflang="no-NO" href="https://www.themoviedb.org/movie?language=no-NO">
    <link rel="alternate" hreflang="pa-IN" href="https://www.themoviedb.org/movie?language=pa-IN">
    <link rel="alternate" hreflang="pl-PL" href="https://www.themoviedb.org/movie?language=pl-PL">
    <link rel="alternate" hreflang="pt-PT" href="https://www.themoviedb.org/movie?language=pt-PT">
    <link rel="alternate" hreflang="ro-RO" href="https://www.themoviedb.org/movie?language=ro-RO">
    <link rel="alternate" hreflang="ru-RU" href="https://www.themoviedb.org/movie?language=ru-RU">
    <link rel="alternate" hreflang="si-LK" href="https://www.themoviedb.org/movie?language=si-LK">
    <link rel="alternate" hreflang="sk-SK" href="https://www.themoviedb.org/movie?language=sk-SK">
    <link rel="alternate" hreflang="sl-SI" href="https://www.themoviedb.org/movie?language=sl-SI">
    <link rel="alternate" hreflang="so-SO" href="https://www.themoviedb.org/movie?language=so-SO">
    <link rel="alternate" hreflang="sq-AL" href="https://www.themoviedb.org/movie?language=sq-AL">
    <link rel="alternate" hreflang="sr-RS" href="https://www.themoviedb.org/movie?language=sr-RS">
    <link rel="alternate" hreflang="sv-SE" href="https://www.themoviedb.org/movie?language=sv-SE">
    <link rel="alternate" hreflang="sw-TZ" href="https://www.themoviedb.org/movie?language=sw-TZ">
    <link rel="alternate" hreflang="ta-IN" href="https://www.themoviedb.org/movie?language=ta-IN">
    <link rel="alternate" hreflang="te-IN" href="https://www.themoviedb.org/movie?language=te-IN">
    <link rel="alternate" hreflang="tl-PH" href="https://www.themoviedb.org/movie?language=tl-PH">
    <link rel="alternate" hreflang="th-TH" href="https://www.themoviedb.org/movie?language=th-TH">
    <link rel="alternate" hreflang="tr-TR" href="https://www.themoviedb.org/movie?language=tr-TR">
    <link rel="alternate" hreflang="uk-UA" href="https://www.themoviedb.org/movie?language=uk-UA">
    <link rel="alternate" hreflang="ur-PK" href="https://www.themoviedb.org/movie?language=ur-PK">
    <link rel="alternate" hreflang="uz-UZ" href="https://www.themoviedb.org/movie?language=uz-UZ">
    <link rel="alternate" hreflang="vi-VN" href="https://www.themoviedb.org/movie?language=vi-VN">
    <link rel="alternate" hreflang="zh-CN" href="https://www.themoviedb.org/movie?language=zh-CN">
    <link rel="alternate" hreflang="zu-ZA" href="https://www.themoviedb.org/movie?language=zu-ZA">
    <link rel="alternate" hreflang="ar-AE" href="https://www.themoviedb.org/movie?language=ar-AE">
    <link rel="alternate" hreflang="ar-BH" href="https://www.themoviedb.org/movie?language=ar-BH">
    <link rel="alternate" hreflang="ar-EG" href="https://www.themoviedb.org/movie?language=ar-EG">
    <link rel="alternate" hreflang="ar-IQ" href="https://www.themoviedb.org/movie?language=ar-IQ">
    <link rel="alternate" hreflang="ar-JO" href="https://www.themoviedb.org/movie?language=ar-JO">
    <link rel="alternate" hreflang="ar-LY" href="https://www.themoviedb.org/movie?language=ar-LY">
    <link rel="alternate" hreflang="ar-MA" href="https://www.themoviedb.org/movie?language=ar-MA">
    <link rel="alternate" hreflang="ar-QA" href="https://www.themoviedb.org/movie?language=ar-QA">
    <link rel="alternate" hreflang="ar-YE" href="https://www.themoviedb.org/movie?language=ar-YE">
    <link rel="alternate" hreflang="ar-TD" href="https://www.themoviedb.org/movie?language=ar-TD">
    <link rel="alternate" hreflang="ca-AD" href="https://www.themoviedb.org/movie?language=ca-AD">
    <link rel="alternate" hreflang="de-AT" href="https://www.themoviedb.org/movie?language=de-AT">
    <link rel="alternate" hreflang="de-CH" href="https://www.themoviedb.org/movie?language=de-CH">
    <link rel="alternate" hreflang="el-CY" href="https://www.themoviedb.org/movie?language=el-CY">
    <link rel="alternate" hreflang="en-AG" href="https://www.themoviedb.org/movie?language=en-AG">
    <link rel="alternate" hreflang="en-AU" href="https://www.themoviedb.org/movie?language=en-AU">
    <link rel="alternate" hreflang="en-BB" href="https://www.themoviedb.org/movie?language=en-BB">
    <link rel="alternate" hreflang="en-BZ" href="https://www.themoviedb.org/movie?language=en-BZ">
    <link rel="alternate" hreflang="en-CA" href="https://www.themoviedb.org/movie?language=en-CA">
    <link rel="alternate" hreflang="en-CM" href="https://www.themoviedb.org/movie?language=en-CM">
    <link rel="alternate" hreflang="en-GB" href="https://www.themoviedb.org/movie?language=en-GB">
    <link rel="alternate" hreflang="en-GG" href="https://www.themoviedb.org/movie?language=en-GG">
    <link rel="alternate" hreflang="en-GH" href="https://www.themoviedb.org/movie?language=en-GH">
    <link rel="alternate" hreflang="en-GI" href="https://www.themoviedb.org/movie?language=en-GI">
    <link rel="alternate" hreflang="en-GY" href="https://www.themoviedb.org/movie?language=en-GY">
    <link rel="alternate" hreflang="en-IE" href="https://www.themoviedb.org/movie?language=en-IE">
    <link rel="alternate" hreflang="en-JM" href="https://www.themoviedb.org/movie?language=en-JM">
    <link rel="alternate" hreflang="en-KE" href="https://www.themoviedb.org/movie?language=en-KE">
    <link rel="alternate" hreflang="en-LC" href="https://www.themoviedb.org/movie?language=en-LC">
    <link rel="alternate" hreflang="en-MW" href="https://www.themoviedb.org/movie?language=en-MW">
    <link rel="alternate" hreflang="en-NZ" href="https://www.themoviedb.org/movie?language=en-NZ">
    <link rel="alternate" hreflang="en-PG" href="https://www.themoviedb.org/movie?language=en-PG">
    <link rel="alternate" hreflang="en-TC" href="https://www.themoviedb.org/movie?language=en-TC">
    <link rel="alternate" hreflang="en-ZM" href="https://www.themoviedb.org/movie?language=en-ZM">
    <link rel="alternate" hreflang="en-ZW" href="https://www.themoviedb.org/movie?language=en-ZW">
    <link rel="alternate" hreflang="es-AR" href="https://www.themoviedb.org/movie?language=es-AR">
    <link rel="alternate" hreflang="es-CL" href="https://www.themoviedb.org/movie?language=es-CL">
    <link rel="alternate" hreflang="es-DO" href="https://www.themoviedb.org/movie?language=es-DO">
    <link rel="alternate" hreflang="es-EC" href="https://www.themoviedb.org/movie?language=es-EC">
    <link rel="alternate" hreflang="es-GT" href="https://www.themoviedb.org/movie?language=es-GT">
    <link rel="alternate" hreflang="es-GQ" href="https://www.themoviedb.org/movie?language=es-GQ">
    <link rel="alternate" hreflang="es-HN" href="https://www.themoviedb.org/movie?language=es-HN">
    <link rel="alternate" hreflang="es-MX" href="https://www.themoviedb.org/movie?language=es-MX">
    <link rel="alternate" hreflang="es-NI" href="https://www.themoviedb.org/movie?language=es-NI">
    <link rel="alternate" hreflang="es-PA" href="https://www.themoviedb.org/movie?language=es-PA">
    <link rel="alternate" hreflang="es-PE" href="https://www.themoviedb.org/movie?language=es-PE">
    <link rel="alternate" hreflang="es-PY" href="https://www.themoviedb.org/movie?language=es-PY">
    <link rel="alternate" hreflang="es-SV" href="https://www.themoviedb.org/movie?language=es-SV">
    <link rel="alternate" hreflang="es-UY" href="https://www.themoviedb.org/movie?language=es-UY">
    <link rel="alternate" hreflang="fr-BF" href="https://www.themoviedb.org/movie?language=fr-BF">
    <link rel="alternate" hreflang="fr-CA" href="https://www.themoviedb.org/movie?language=fr-CA">
    <link rel="alternate" hreflang="fr-CD" href="https://www.themoviedb.org/movie?language=fr-CD">
    <link rel="alternate" hreflang="fr-CI" href="https://www.themoviedb.org/movie?language=fr-CI">
    <link rel="alternate" hreflang="fr-GF" href="https://www.themoviedb.org/movie?language=fr-GF">
    <link rel="alternate" hreflang="fr-GP" href="https://www.themoviedb.org/movie?language=fr-GP">
    <link rel="alternate" hreflang="fr-MC" href="https://www.themoviedb.org/movie?language=fr-MC">
    <link rel="alternate" hreflang="fr-ML" href="https://www.themoviedb.org/movie?language=fr-ML">
    <link rel="alternate" hreflang="fr-MU" href="https://www.themoviedb.org/movie?language=fr-MU">
    <link rel="alternate" hreflang="fr-PF" href="https://www.themoviedb.org/movie?language=fr-PF">
    <link rel="alternate" hreflang="it-VA" href="https://www.themoviedb.org/movie?language=it-VA">
    <link rel="alternate" hreflang="ms-SG" href="https://www.themoviedb.org/movie?language=ms-SG">
    <link rel="alternate" hreflang="nl-BE" href="https://www.themoviedb.org/movie?language=nl-BE">
    <link rel="alternate" hreflang="pt-AO" href="https://www.themoviedb.org/movie?language=pt-AO">
    <link rel="alternate" hreflang="pt-BR" href="https://www.themoviedb.org/movie?language=pt-BR">
    <link rel="alternate" hreflang="pt-MZ" href="https://www.themoviedb.org/movie?language=pt-MZ">
    <link rel="alternate" hreflang="ro-MD" href="https://www.themoviedb.org/movie?language=ro-MD">
    <link rel="alternate" hreflang="sr-ME" href="https://www.themoviedb.org/movie?language=sr-ME">
    <link rel="alternate" hreflang="sq-XK" href="https://www.themoviedb.org/movie?language=sq-XK">
    <link rel="alternate" hreflang="zh-HK" href="https://www.themoviedb.org/movie?language=zh-HK">
    <link rel="alternate" hreflang="zh-SG" href="https://www.themoviedb.org/movie?language=zh-SG">
    <link rel="alternate" hreflang="zh-TW" href="https://www.themoviedb.org/movie?language=zh-TW">

      <script src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js" type="text/javascript" charset="UTF-8" data-domain-script="23223fbb-5c84-48df-836d-0a83fb7b2c03"></script>
      <script>function OptanonWrapper() {}</script>
    <script src="/assets/2/lozad.min-7f803337d01a657607bca6b20e06f371c3895b36a5f2be03a8fa9b5e16c9a83e.js"></script>
    <script src="/assets/2/jquery-3.6.0.min-ff1523fb7389539c84c65aba19260648793bb4f5e29329d2ee8804bc37a3fe6e.js"></script>
    <script src="/assets/2/kendo-93daa31ab3dcca8723478255a3b3c3f0a9e6672dddc612e114391786423c1870.js"></script>
      <script src="/assets/2/kendo-2021.1.204/cultures/kendo.culture.en-US.min-61ce5636474a35333ecff74fe30c528d459bcee29b3b32fc0c58ac77de788b34.js"></script>
      <script src="/assets/2/kendo-2021.1.204/messages/kendo.messages.en-US.min-79da68ae0221b4fd7978805d0c79cc7f682fddace5f2137aa0dae8fe1c5ddacd.js"></script>
    <script src="/assets/2/application-365501d0f2bb3e2b4dceec07a6fd380428faba303d1e80e2a0b837edfd5a2c57.js"></script>
    <script src="/assets/2/pusher.min-ee61b1e19799dd5aae92a3d91bc970e6147c6fe4395eacf3e499ed1451650f22.js"></script>
      <script src="/assets/2/application.desktop-ea69249141a43ef7c6a59a19ee40eface5e171cf03eefffddb488574a66dea02.js" defer></script>
      <script src="/assets/2/kendo-2021.1.204/kendo.calendar.min-ff597f14a778b702ec1cf9967dec754e429caf1558c8b89f0de036e8efe39761.js" defer></script>
      <script src="/assets/2/kendo-2021.1.204/kendo.datepicker.min-9efa21cba900555da428262129f44042706c5abac5644c872d9cac78f010493a.js" defer></script>
      <script src="/assets/2/kendo-2021.1.204/kendo.slider.min-1e770b8fc7facf8ee48d3b0ad7abdfb598ab17cb69add240accc8df5fa2bc919.js" defer></script>
    <script>
      window.mobileDevice = false;
      detected_timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
        timezone = detected_timezone;
      kendo.culture("en-US");
    </script>
      <script>
        (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-5QWVXV');
      </script>

1.d. Infer the type of the variable created in part 1c and display the first 200 characters of
the content from the server’s response

In [ ]:
print("the type of the variable 'page_content' is:", type(page_content))

the type of the variable 'page_content' is: <class 'str'>

In [ ]:
print("the first 200 characters of the content from the server's response are:")
print(page_content[:200])

the first 200 characters of the content from the server's response are:
<!DOCTYPE html>
<html lang="en" class="no-js">
  <head>
    <title>Popular Movies &#8212; The Movie Database (TMDB)</title>
    <meta http-equiv="cleartype" content="on">
    <meta charset="utf-8">

2. Parse the content of HTML response using the BeautifulSoup library and execute the tasks
specified in the guidelines mentioned below ( 6 marks )

2.a. From the BeautifulSoup library (bs4) import the BeautifulSoup class. Pass the contents
of the webpage obtained from step 1c as an argument to create an instance of the
BeautifulSoup class
Hint : Use “ html.parser ” as another argument of the BeautifulSoup constructor function
(https://www.crummy.com/software/BeautifulSoup/bs4/doc/#making-the-soup)

In [ ]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(page_content, 'html.parser')

2.b. Extract the title of the parsed web page content using an appropriate method or
attribute of the document object created in part 2a
(https://www.crummy.com/software/BeautifulSoup/bs4/doc/#navigating-using-tag
names)

In [ ]:
title = soup.title.string
print(title)

Popular Movies — The Movie Database (TMDB)

2.c. Write a user defined function to generalize the task presented in Q2a to any URL that
retrieves the content of the webpage. Your function should take a URL string as an input
and return a correctly formulated BeautifulSoup instance as the output. In your
function definition, ensure that appropriate exceptions are raised to the user (through
status codes) if they pass in malformed/incorrect URLs. Write two test cases for your
function - one with a working URL and another with an URL that gets a 404 response. (
3 marks )
Note: While pulling the request please specify a user agent string as showed in Q.1.

In [ ]:
def url_converter(url):
  needed_headers = {'User-Agent': "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36",'Accept-Language': 'en'}
  response = requests.get(url,headers=needed_headers)
  if(response.status_code == 200):
        content_of_webpage = response.text
        souped_url = BeautifulSoup(content_of_webpage, 'html.parser')
        print("successfully parsed:",response.status_code)
        return souped_url
  else:
      print("error in URL:",response.status_code)
#testcases:
#testcase 1: Working URL
print("testcase 1- Working URL:")
url_converter("https://www.themoviedb.org/")

#testcase 2: Broken URL
print("testcase 2- Broken URL:")
url_converter("https://www.themoviedb.org/fwef")

testcase 1- Working URL:
successfully parsed: 200
testcase 2- Broken URL:
error in URL: 404

3. Extract the content of the webpage - https://www.themoviedb.org/movie - that hosts a
current dated listing of popular movies.

3.a. Write a function call to the user defined function created in 2c with the url
https://www.themoviedb.org/movie as an input and store the response in a variable (
1 mark )

In [ ]:
soup_movie = url_converter("https://www.themoviedb.org/movie")

successfully parsed: 200

Apply appropriate methods from the BeautifulSoup library
(https://www.crummy.com/software/BeautifulSoup/bs4/doc/#making-the-soup) on the variable created
in part 3a to answer the following questions:

3.b. Print the HTML content associated with the first movie displayed on the web page using
appropriate HTML tags to access this listing on the object created in part 3a ( 1 mark ) c.
Display the name of the first movie using appropriate HTML tags to access this listing on
the object created in part 3a ( 1 mark )

In [ ]:
#soup.find("div", class_="card style_1") OR we can use below code to specify the movie by index
soup_movie.find_all("div", class_="card style_1")[0]

<div class="card style_1">
<div class="image">
<div class="wrapper glyphicons_v2 picture grey no_image_holder">
<a class="image" href="/movie/533535-deadpool-wolverine" title="Deadpool &amp; Wolverine">
<img alt="Deadpool &amp; Wolverine" class="poster w-full" loading="lazy" src="https://media.themoviedb.org/t/p/w220_and_h330_face/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg" srcset="https://media.themoviedb.org/t/p/w220_and_h330_face/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg 1x, https://media.themoviedb.org/t/p/w440_and_h660_face/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg 2x"/>
</a>
</div>
<div class="options" data-id="533535" data-media-type="movie" data-object-id="5b3b6b8ec3a3684b8900d8fd">
<a aria-label="View Item Options" class="no_click" href="#"><div class="glyphicons_v2 circle-more white"></div></a>
</div>
</div>
<div class="content">
<div class="consensus tight">
<div class="outer_ring">
<div class="user_score_chart 5b3b6b8ec3a3684b8900d8fd" data-bar-color="#21d07a" data-percent="78" data-track-color="#204529">
<div class="percent">
<span class="icon icon-r78"></span>
</div>
</div>
</div>
</div>
<h2><a href="/movie/533535-deadpool-wolverine" title="Deadpool &amp; Wolverine">Deadpool &amp; Wolverine</a></h2>
<p>Jul 26, 2024</p>
</div>
<div class="hover 533535"></div>
</div>

3.c.
Display the name of the first movie using appropriate HTML tags to access this listing on
the object created in part 3a ( 1 mark )

In [ ]:
soup_movie.find("div",class_ = "card style_1").find('h2').text

'Deadpool & Wolverine'

3.d. Display the user rating of the first movie by using appropriate HTML tags to access this
listing on the object created in part 3a (1 mark )

In [ ]:
soup_movie.find("div",class_ = "card style_1").find('div', class_ ='user_score_chart').get("data-percent")

'78'

3.e. For the first movie, extract the part of the url following the string
“https://www.themoviedb.org/” using the appropriate HTML tags to extract this portion
on the object created in part 3a (do not use built-in string methods). (1 mark )
For example, if the first movie on the web page had the URL
https://www.themoviedb.org/movie/779782 “ your output should be movie/779782

In [ ]:
soup.find("div",class_ = "card style_1").find('a').get("href")

'/movie/533535-deadpool-wolverine'

4.a.Write a user defined function for:  Titles of all the movies on the page as a Python list

In [ ]:
def get_movie_titles(soup_movie):
    movie_titles = []
    for movie in soup_movie.find_all("div", class_="card style_1"):
        title = movie.find("h2").text.strip()
        movie_titles.append(title)  # Append the title to the list
    return movie_titles

# Example:
movie_titles = get_movie_titles(soup_movie)
movie_titles

['Deadpool & Wolverine',
 'Twisters',
 'Inside Out 2',
 'Despicable Me 4',
 'Bad Boys: Ride or Die',
 'Kill',
 'Dragonkeeper',
 'It Ends with Us',
 'A Quiet Place: Day One',
 'Prey',
 'Alien: Romulus',
 'Saving Bikini Bottom: The Sandy Cheeks Movie',
 'Mayhem!',
 'One Fast Move',
 'The Instigators',
 'Furiosa: A Mad Max Saga',
 'Kingdom of the Planet of the Apes',
 'The Garfield Movie',
 'The Convert',
 'Paradox Effect']

4.b. User ratings of all the movies on the page as a Python list

In [ ]:
def get_user_ratings(soup_movie):
    user_ratings = []
    for movie in soup_movie.find_all("div",class_ = "card style_1"):
      if movie.find('div', class_ ='user_score_chart') == 'null':
        user_ratings.append("not rated")
      else:
        user_ratings.append(movie.find('div', class_ ='user_score_chart').get("data-percent"))
    return user_ratings

# Example:
user_ratings = get_user_ratings(soup_movie)
user_ratings

['78',
 '71',
 '76',
 '73',
 '76',
 '70',
 '72',
 '71',
 '69',
 '65',
 '73',
 '64',
 '67',
 '68',
 '64',
 '76',
 '72',
 '72',
 '63',
 '64']

4.C. HTML content of all the individual pages of movies collected into a Python list

In [ ]:
def get_movie_pages(soup_movie):
    movie_pages = []
    for movie in soup_movie.find_all("div",class_ = "card style_1"):
        movie_pages.append(movie.find('a').get("href"))
    return movie_pages

#Example
movie_pages = get_movie_pages(soup_movie)
movie_pages

['/movie/533535-deadpool-wolverine',
 '/movie/718821-twisters',
 '/movie/1022789-inside-out-2',
 '/movie/519182-despicable-me-4',
 '/movie/573435-bad-boys-ride-or-die',
 '/movie/1160018-kill',
 '/movie/588648-dragonkeeper',
 '/movie/1079091-it-ends-with-us',
 '/movie/762441-a-quiet-place-day-one',
 '/movie/1129598-prey',
 '/movie/945961-alien-romulus',
 '/movie/831815-saving-bikini-bottom-the-sandy-cheeks-movie',
 '/movie/959092-farang',
 '/movie/1281826-one-fast-move',
 '/movie/1059064-the-instigators',
 '/movie/786892-furiosa-a-mad-max-saga',
 '/movie/653346-kingdom-of-the-planet-of-the-apes',
 '/movie/748783-the-garfield-movie',
 '/movie/1066262-the-convert',
 '/movie/1064375-paradox-effect']

4.d. Genres of all the movies on the page as a Python list

In [ ]:
def get_movie_generes(soup_movie):
  all_movie_generes = []
  movie_pages = get_movie_pages(soup_movie)
  for movie_page in movie_pages:
    url = "https://www.themoviedb.org" + movie_page
    needed_headers = {'User-Agent': "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36",'Accept-Language': 'en'}
    response = requests.get(url,headers = needed_headers) # Get the response
    response.raise_for_status() # Checking for HTTP errors
    movie_soup = BeautifulSoup(response.content, 'html.parser') # Pass the HTML content to BeautifulSoup
    #all generes
    genere_section = movie_soup.find('span', class_='genres')
    if genere_section:
         genere_list = genere_section.find_all('a')
         movie_genere = [genere_member.get('href').split('/')[2].split('-')[1] for genere_member in genere_list]
         all_movie_generes.append(movie_genere)
    else:
         all_movie_generes.append([])  # Append an empty list if no cast found
  return all_movie_generes

#Example
movie_generes = get_movie_generes(soup_movie)
print(movie_generes)

[['action', 'comedy', 'science'], ['action', 'adventure', 'drama', 'thriller'], ['animation', 'family', 'adventure', 'comedy'], ['animation', 'family', 'comedy', 'action'], ['action', 'crime', 'thriller', 'comedy'], ['action', 'crime'], ['action', 'adventure', 'animation', 'family', 'fantasy'], ['romance', 'drama'], ['horror', 'science', 'thriller'], ['action', 'thriller'], ['horror', 'science'], ['animation', 'comedy', 'adventure', 'family'], ['action', 'crime', 'drama'], ['action', 'drama', 'romance'], ['action', 'comedy', 'crime'], ['action', 'adventure', 'science'], ['science', 'adventure', 'action'], ['animation', 'comedy', 'family', 'adventure', 'action'], ['action', 'drama'], ['action', 'thriller']]

4.e. Cast of all the movies on the page as a Python list

In [ ]:
import requests
from bs4 import BeautifulSoup

def get_movie_cast(soup_movie):
    all_movie_cast = []
    movie_pages = get_movie_pages(soup_movie)
    for movie_page in movie_pages:
        url = "https://www.themoviedb.org" + movie_page
        needed_headers = {'User-Agent': "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36",'Accept-Language': 'en'}
        response = requests.get(url,headers = needed_headers)
        response.raise_for_status()
        movie_soup = BeautifulSoup(response.content, 'html.parser')

        # Find the cast section
        cast_section = movie_soup.find('ol', class_='people scroller')
        if cast_section:
            cast_list = cast_section.find_all('li', class_='card')
            movie_cast = [cast_member.find('p').text.strip() for cast_member in cast_list]
            all_movie_cast.append(movie_cast)
        else:
            all_movie_cast.append([])  # Append an empty list if no cast found

    return all_movie_cast

# Example)
movie_cast_list = get_movie_cast(soup_movie)
print(movie_cast_list)

[['Ryan Reynolds', 'Hugh Jackman', 'Emma Corrin', 'Matthew Macfadyen', 'Dafne Keen', 'Jon Favreau', 'Morena Baccarin', 'Rob Delaney', 'Leslie Uggams'], ['Daisy Edgar-Jones', 'Glen Powell', 'Anthony Ramos', 'Brandon Perea', 'Maura Tierney', 'Harry Hadden-Paton', 'Sasha Lane', 'Daryl McCormack', 'Kiernan Shipka'], ['Amy Poehler', 'Maya Hawke', 'Kensington Tallman', 'Liza Lapira', 'Phyllis Smith', 'Lewis Black', 'Tony Hale', 'Ayo Edebiri', 'Adèle Exarchopoulos'], ['Steve Carell', 'Kristen Wiig', 'Will Ferrell', 'Sofía Vergara', 'Miranda Cosgrove', 'Dana Gaier', 'Madison Polan', 'Pierre Coffin', 'Chris Renaud'], ['Will Smith', 'Martin Lawrence', 'Vanessa Hudgens', 'Alexander Ludwig', 'Paola Nuñez', 'Eric Dane', 'Ioan Gruffudd', 'Jacob Scipio', 'Melanie Liburd'], ['Lakshya Lalwani', 'Raghav Juyal', 'Tanya Maniktala', 'Abhishek Chauhan', 'Ashish Vidhyarthi', 'Adrija Sinha', 'Harsh Chhaya', 'Parth Tiwari', 'Akshay Vichare'], ['Lucía Pérez', 'Mario Gas', 'Fernando Castro', 'Carlos de Luna', 'José Gómez Adán', 'César Díaz Capilla', 'Isabel Gaudí', 'Miquel Rodríguez Ros', 'Álvaro Navarro'], ['Blake Lively', 'Justin Baldoni', 'Brandon Sklenar', 'Jenny Slate', 'Hasan Minhaj', 'Amy Morton', 'Kevin McKidd', 'Isabela Ferrer', 'Alex Neustaedter'], ["Lupita Nyong'o", 'Joseph Quinn', 'Alex Wolff', 'Djimon Hounsou', 'Eliane Umuhire', 'Takunda Khumalo', 'Alfie Todd', 'Avy-Berry Worrall', 'Ronnie Le Drew'], ['Ryan Phillippe', 'Emile Hirsch', 'Mena Suvari', 'Dylan Flashner', 'Tristan Thompson', 'Michaela Sasner', 'Jeremy Tardy', 'Mohamed Hakeemshady', 'Alpha Miknas'], ['Cailee Spaeny', 'David Jonsson', 'Archie Renaux', 'Isabela Merced', 'Spike Fearn', 'Aileen Wu', 'Rosie Ede', 'Soma Simon', 'Bence Okeke'], ['Carolyn Lawrence', 'Tom Kenny', 'Clancy Brown', 'Bill Fagerbakke', 'Mr. Lawrence', 'Rodger Bumpass', 'Johnny Knoxville', 'Craig Robinson', 'Grey DeLisle'], ['Nassim Lyes', 'Loryn Nounay', 'Olivier Gourmet', 'Vithaya Pansringarm', 'Mehdi Hadim', 'Kenneth Won', 'Sahajak Boonthanakit', 'Chananticha Chaipa', 'Boonsong Nakphoo'], ['K.J. Apa', 'Eric Dane', 'Maia Reficco', 'Edward James Olmos', 'Austin North', 'Jackson Hurst', 'Adam Thomas Ziemba', 'Libby Blake', 'Kevin Saunders'], ['Matt Damon', 'Casey Affleck', 'Hong Chau', 'Michael Stuhlbarg', 'Paul Walter Hauser', 'Ving Rhames', 'Alfred Molina', 'Toby Jones', 'Jack Harlow'], ['Anya Taylor-Joy', 'Chris Hemsworth', 'Tom Burke', 'Alyla Browne', 'George Shevtsov', 'Lachy Hulme', 'John Howard', 'Angus Sampson', 'Charlee Fraser'], ['Owen Teague', 'Freya Allan', 'Kevin Durand', 'Peter Macon', 'William H. Macy', 'Eka Darville', 'Travis Jeffery', 'Lydia Peckham', 'Neil Sandilands'], ['Chris Pratt', 'Samuel L. Jackson', 'Hannah Waddingham', 'Ving Rhames', 'Nicholas Hoult', 'Cecily Strong', 'Harvey Guillén', 'Brett Goldstein', 'Bowen Yang'], ['Guy Pearce', 'Tioreore Ngatai-Melbourne', 'Antonio Te Maioha', 'Jacqueline McKenzie', 'Te Kohe Tuhaka', 'Lawrence Makoare', "Dean O'Gorman", 'Jared Turner', 'Kelly Vivian'], ['Olga Kurylenko', 'Harvey Keitel', 'Oliver Trevena', 'Alice Astons', 'Talia Asseraf', 'Meredith Mickelson', 'Malich Cissé', 'Lucia Zotti', 'Paul Sampson']]

5.a. User defined functions that return pandas dataframe: Titles of the movies listed on the page

In [ ]:
import pandas as pd

In [ ]:
def get_movie_titles_df(soup_movie):
    movie_titles = get_movie_titles(soup_movie)
    df = pd.DataFrame({'Movie Titles': movie_titles})
    return df

# Example:
get_movie_titles_df(soup_movie)

                                    Movie Titles
0                           Deadpool & Wolverine
1                                       Twisters
2                                   Inside Out 2
3                                Despicable Me 4
4                          Bad Boys: Ride or Die
5                                           Kill
6                                   Dragonkeeper
7                                It Ends with Us
8                         A Quiet Place: Day One
9                                           Prey
10                                Alien: Romulus
11  Saving Bikini Bottom: The Sandy Cheeks Movie
12                                       Mayhem!
13                                 One Fast Move
14                               The Instigators
15                       Furiosa: A Mad Max Saga
16             Kingdom of the Planet of the Apes
17                            The Garfield Movie
18                                   The Convert
19                                Paradox Effect

5.b. User ratings of the movies listed on the page

In [ ]:
def get_user_ratings_df(soup_movie):
    user_ratings = get_user_ratings(soup_movie)
    df = pd.DataFrame({'User Ratings': user_ratings})
    return df

# Example:
get_user_ratings_df(soup_movie)

   User Ratings
0            78
1            71
2            76
3            73
4            76
5            70
6            72
7            71
8            69
9            65
10           73
11           64
12           67
13           68
14           64
15           76
16           72
17           72
18           63
19           64

5.c. Genres of the movies listed on the page

In [ ]:
def get_movie_generes_df(soup_movie):
    movie_genere = get_movie_generes(soup_movie)
    df = pd.DataFrame({'Movie Generes': movie_genere})
    return df

# Example:
#movie_titles_df = get_movie_titles_df(soup_movie)
get_movie_generes_df(soup_movie)

                                      Movie Generes
0                         [action, comedy, science]
1              [action, adventure, drama, thriller]
2            [animation, family, adventure, comedy]
3               [animation, family, comedy, action]
4                 [action, crime, thriller, comedy]
5                                   [action, crime]
6   [action, adventure, animation, family, fantasy]
7                                  [romance, drama]
8                       [horror, science, thriller]
9                                [action, thriller]
10                                [horror, science]
11           [animation, comedy, adventure, family]
12                           [action, crime, drama]
13                         [action, drama, romance]
14                          [action, comedy, crime]
15                     [action, adventure, science]
16                     [science, adventure, action]
17   [animation, comedy, family, adventure, action]
18                                  [action, drama]
19                               [action, thriller]

5.d. Cast of the movies listed on the page

In [ ]:
def get_movie_cast_df(soup_movie):
    cast_movie = get_movie_cast(soup_movie)
    df = pd.DataFrame({'Cast': cast_movie})
    return df

# Example:
#movie_titles_df = get_movie_titles_df(soup_movie)
get_movie_cast_df(soup_movie)

                                                 Cast
0   [Ryan Reynolds, Hugh Jackman, Emma Corrin, Mat...
1   [Daisy Edgar-Jones, Glen Powell, Anthony Ramos...
2   [Amy Poehler, Maya Hawke, Kensington Tallman, ...
3   [Steve Carell, Kristen Wiig, Will Ferrell, Sof...
4   [Will Smith, Martin Lawrence, Vanessa Hudgens,...
5   [Lakshya Lalwani, Raghav Juyal, Tanya Maniktal...
6   [Lucía Pérez, Mario Gas, Fernando Castro, Carl...
7   [Blake Lively, Justin Baldoni, Brandon Sklenar...
8   [Lupita Nyong'o, Joseph Quinn, Alex Wolff, Dji...
9   [Ryan Phillippe, Emile Hirsch, Mena Suvari, Dy...
10  [Cailee Spaeny, David Jonsson, Archie Renaux, ...
11  [Carolyn Lawrence, Tom Kenny, Clancy Brown, Bi...
12  [Nassim Lyes, Loryn Nounay, Olivier Gourmet, V...
13  [K.J. Apa, Eric Dane, Maia Reficco, Edward Jam...
14  [Matt Damon, Casey Affleck, Hong Chau, Michael...
15  [Anya Taylor-Joy, Chris Hemsworth, Tom Burke, ...
16  [Owen Teague, Freya Allan, Kevin Durand, Peter...
17  [Chris Pratt, Samuel L. Jackson, Hannah Waddin...
18  [Guy Pearce, Tioreore Ngatai-Melbourne, Antoni...
19  [Olga Kurylenko, Harvey Keitel, Oliver Trevena...

6.a. Write a function that scrapes data (mentioned in Q5) from page number 1, 2, 3, 4 and 5 on
the URL https://www.themoviedb.org/movie and returns 5 data frames which can be exported
to csv file by calling the functions defined in Q3a, Q4c and Q5 (3 marks)
Hint : use the string “ ?page={ } “ concatenated to the string
“ https://www.themoviedb.org/movie “ which extracts the data from desired page no passed to
page value

In [ ]:
import pandas as pd

def scrape_movie_and_export():
    dataframes = []
    for page_number in range(1, 6):
        url = "https://www.themoviedb.org/movie" + f"?page={page_number}"
        soup_new = url_converter(url)  # Using your function from 2c
        title_df = get_movie_titles_df(soup_new)
        ratings_df = get_user_ratings_df(soup_new)
        genres_df = get_movie_generes_df(soup_new)
        cast_df = get_movie_cast_df(soup_new)

        # Combine the dataframes for this page
        pages_df = pd.concat([title_df, ratings_df, genres_df, cast_df], axis=1)
        dataframes.append(pages_df)

        # Optionally, export each page's dataframe to a CSV
        pages_df.to_csv(f"movie_data_page{page_number}.csv", index=False)

    return dataframes

In [ ]:
scrape_movie_and_export()

successfully parsed: 200
successfully parsed: 200
successfully parsed: 200
successfully parsed: 200
successfully parsed: 200

[                                    Movie Titles User Ratings  \
 0                           Deadpool & Wolverine           78
 1                                       Twisters           71
 2                                   Inside Out 2           76
 3                                Despicable Me 4           73
 4                          Bad Boys: Ride or Die           76
 5                                           Kill           70
 6                                   Dragonkeeper           72
 7                                It Ends with Us           71
 8                         A Quiet Place: Day One           69
 9                                           Prey           65
 10                                Alien: Romulus           73
 11  Saving Bikini Bottom: The Sandy Cheeks Movie           64
 12                                       Mayhem!           67
 13                                 One Fast Move           68
 14                               The Instigators           64
 15                       Furiosa: A Mad Max Saga           76
 16             Kingdom of the Planet of the Apes           72
 17                            The Garfield Movie           72
 18                                   The Convert           63
 19                                Paradox Effect           64

                                       Movie Generes  \
 0                         [action, comedy, science]
 1              [action, adventure, drama, thriller]
 2            [animation, family, adventure, comedy]
 3               [animation, family, comedy, action]
 4                 [action, crime, thriller, comedy]
 5                                   [action, crime]
 6   [action, adventure, animation, family, fantasy]
 7                                  [romance, drama]
 8                       [horror, science, thriller]
 9                                [action, thriller]
 10                                [horror, science]
 11           [animation, comedy, adventure, family]
 12                           [action, crime, drama]
 13                         [action, drama, romance]
 14                          [action, comedy, crime]
 15                     [action, adventure, science]
 16                     [science, adventure, action]
 17   [animation, comedy, family, adventure, action]
 18                                  [action, drama]
 19                               [action, thriller]

                                                  Cast
 0   [Ryan Reynolds, Hugh Jackman, Emma Corrin, Mat...
 1   [Daisy Edgar-Jones, Glen Powell, Anthony Ramos...
 2   [Amy Poehler, Maya Hawke, Kensington Tallman, ...
 3   [Steve Carell, Kristen Wiig, Will Ferrell, Sof...
 4   [Will Smith, Martin Lawrence, Vanessa Hudgens,...
 5   [Lakshya Lalwani, Raghav Juyal, Tanya Maniktal...
 6   [Lucía Pérez, Mario Gas, Fernando Castro, Carl...
 7   [Blake Lively, Justin Baldoni, Brandon Sklenar...
 8   [Lupita Nyong'o, Joseph Quinn, Alex Wolff, Dji...
 9   [Ryan Phillippe, Emile Hirsch, Mena Suvari, Dy...
 10  [Cailee Spaeny, David Jonsson, Archie Renaux, ...
 11  [Carolyn Lawrence, Tom Kenny, Clancy Brown, Bi...
 12  [Nassim Lyes, Loryn Nounay, Olivier Gourmet, V...
 13  [K.J. Apa, Eric Dane, Maia Reficco, Edward Jam...
 14  [Matt Damon, Casey Affleck, Hong Chau, Michael...
 15  [Anya Taylor-Joy, Chris Hemsworth, Tom Burke, ...
 16  [Owen Teague, Freya Allan, Kevin Durand, Peter...
 17  [Chris Pratt, Samuel L. Jackson, Hannah Waddin...
 18  [Guy Pearce, Tioreore Ngatai-Melbourne, Antoni...
 19  [Olga Kurylenko, Harvey Keitel, Oliver Trevena...  ,
                                          Movie Titles User Ratings  \
 0                            Breaking and Re-entering           60
 1                                      The Mouse Trap           26
 2                                  Fly Me to the Moon           71
 3                                       House of Ga'a           59
 4                                      Mission: Cross           70
 5                                              Thelma           70
 6                        Descendants: The Rise of Red           70
 7                                            Jackpot!           65
 8   Justice League: Crisis on Infinite Earths Part...           74
 9                     Godzilla x Kong: The New Empire           72
 10                                              Alien           82
 11                                     Non Negotiable           60
 12              The Ministry of Ungentlemanly Warfare           72
 13                                      The King Tide           71
 14                                    Kung Fu Panda 4           71
 15                                           My Fault           80
 16                                          The Union           63
 17                       Escape from the 21st Century           69
 18                             Avengers: Infinity War           82
 19                                          Civil War           70

                            Movie Generes  \
 0                       [action, comedy]
 1             [horror, thriller, comedy]
 2                      [romance, comedy]
 3                      [action, history]
 4            [action, comedy, adventure]
 5            [action, comedy, adventure]
 6   [fantasy, adventure, family, comedy]
 7              [action, comedy, science]
 8           [animation, science, action]
 9           [science, action, adventure]
 10                     [horror, science]
 11     [action, thriller, comedy, drama]
 12                 [action, comedy, war]
 13          [thriller, mystery, fantasy]
 14  [animation, family, fantasy, action]
 15                      [drama, romance]
 16                      [action, comedy]
 17                     [science, comedy]
 18          [adventure, action, science]
 19                  [war, action, drama]

                                                  Cast
 0   [Chen Bolin, Cecilia Choi, Kent Tsai, JC Lin, ...
 1   [Simon Phillips, Sophie McIntosh, Nick Biskupe...
 2   [Scarlett Johansson, Channing Tatum, Woody Har...
 3   [Femi Branch, Mike Afolarin, Funke Akindele, F...
 4   [Hwang Jung-min, Yum Jung-ah, Jeon Hye-jin, Je...
 5   [June Squibb, Fred Hechinger, Richard Roundtre...
 6   [Kylie Cantrall, Malia Baker, Ruby Rose Turner...
 7   [Awkwafina, John Cena, Simu Liu, Ayden Mayeri,...
 8   [Jensen Ackles, Darren Criss, Corey Stoll, Gid...
 9   [Rebecca Hall, Brian Tyree Henry, Dan Stevens,...
 10  [Tom Skerritt, Sigourney Weaver, Veronica Cart...
 11  [Mauricio Ochmann, Leonardo Ortizgris, Enoc Le...
 12  [Henry Cavill, Eiza González, Alan Ritchson, H...
 13  [Frances Fisher, Clayne Crawford, Lara Jean Ch...
 14  [Jack Black, Awkwafina, Viola Davis, Dustin Ho...
 15  [Nicole Wallace, Gabriel Guevara, Marta Hazas,...
 16  [Mark Wahlberg, Halle Berry, J.K. Simmons, Mik...
 17  [Zhang Ruoyun, Zhong Chuxi, Song Yang, Wu Xiao...
 18  [Robert Downey Jr., Chris Evans, Chris Hemswor...
 19  [Kirsten Dunst, Wagner Moura, Cailee Spaeny, S...  ,
                           Movie Titles User Ratings  \
 0                             Coraline           79
 1              My Spy The Eternal City           67
 2        Shimmy: The First Monkey King           66
 3                      An Ideal Father           65
 4                             Deadpool           76
 5                         The Exorcism           46
 6                  Alice in Terrorland           60
 7                                  xXx           59
 8                      3 Days in Malay           49
 9   BLUE LOCK THE MOVIE -EPISODE NAGI-           84
 10                        Out of Exile           63
 11                         Under Paris           61
 12                            MaXXXine           64
 13                      Johnny & Clyde           48
 14               Stranger in the Woods           63
 15           Beverly Hills Cop: Axel F           68
 16                          Deliver Us           56
 17                           Migration           75
 18                 Underground Monster           44
 19                          Inside Out           79

                                       Movie Generes  \
 0                      [animation, family, fantasy]
 1                                  [action, comedy]
 2   [action, adventure, animation, comedy, fantasy]
 3                                       [drama, tv]
 4                       [action, adventure, comedy]
 5                                [horror, thriller]
 6                                [horror, thriller]
 7              [action, adventure, thriller, crime]
 8                          [action, adventure, war]
 9                        [animation, action, drama]
 10                 [thriller, drama, action, crime]
 11                [action, drama, horror, thriller]
 12               [crime, horror, mystery, thriller]
 13                        [action, thriller, crime]
 14                               [horror, thriller]
 15                          [action, comedy, crime]
 16                                         [horror]
 17   [animation, action, adventure, comedy, family]
 18                             [fantasy, adventure]
 19    [animation, family, adventure, drama, comedy]

                                                  Cast
 0   [Dakota Fanning, Teri Hatcher, Jennifer Saunde...
 1   [Dave Bautista, Chloe Coleman, Kristen Schaal,...
 2                                                  []
 3   [Laurent Gerra, Eddy Mitchell, Laure-Lucille S...
 4   [Ryan Reynolds, Morena Baccarin, Ed Skrein, T....
 5   [Russell Crowe, Ryan Simpkins, Sam Worthington...
 6   [Lizzy Willis, Rula Lenska, Jon-Paul Gates, St...
 7   [Vin Diesel, Asia Argento, Marton Csokas, Samu...
 8   [Louis Mandylor, Donald Cerrone, Quinton 'Ramp...
 9   [Nobunaga Shimazaki, Yuma Uchida, Kazuyuki Oki...
 10  [Adam Hampton, Karrie Cox, Kyle Jacob Henry, R...
 11  [Bérénice Bejo, Nassim Lyes, Léa Léviant, Sand...
 12  [Mia Goth, Elizabeth Debicki, Moses Sumney, Mi...
 13  [Avan Jogia, Ajani Russell, Megan Fox, Tyson R...
 14  [Holly Kenney, Brendin Brown, Paris Nicole, Ra...
 15  [Eddie Murphy, Joseph Gordon-Levitt, Taylour P...
 16  [Lee Roy Kunz, Maria Vera Ratti, Alexander Sid...
 17  [Kumail Nanjiani, Elizabeth Banks, Caspar Jenn...
 18  [Wei Wei, Wei Lu, Zhang Chunzhong, Yue Dongfen...
 19  [Amy Poehler, Phyllis Smith, Richard Kind, Bil...  ,
                                          Movie Titles User Ratings  \
 0                                                Trap           63
 1                          The Jack in the Box: Rises           68
 2   Miraculous World: Paris, Tales of Shadybug and...           73
 3                                        The Fall Guy           72
 4                                                  IF           73
 5                            The Strangers: Chapter 1           59
 6                                          Immaculate           63
 7                                     The Last Breath           67
 8                              Something in the Water           60
 9                                          Deadpool 2           75
 10                                          Yu☆Gi☆Oh!           71
 11                                              Atlas           68
 12                                       The Watchers           65
 13                        Autumn and the Black Jaguar           62
 14                                        The Marvels           61
 15                                      The Godfather           87
 16                                             Aliens           79
 17                                           Alienoid           69
 18                          Late Night with the Devil           73
 19                           May the 12th Be with You           56

                                       Movie Generes  \
 0                                 [crime, thriller]
 1                                          [horror]
 2   [animation, adventure, action, fantasy, family]
 3                                  [action, comedy]
 4                         [comedy, fantasy, family]
 5                                [horror, thriller]
 6                       [horror, mystery, thriller]
 7                                [thriller, horror]
 8                                [thriller, horror]
 9                       [action, comedy, adventure]
 10                  [adventure, animation, fantasy]
 11                                [science, action]
 12             [horror, fantasy, mystery, thriller]
 13                              [adventure, family]
 14                     [science, adventure, action]
 15                                   [drama, crime]
 16                      [action, thriller, science]
 17            [science, action, fantasy, adventure]
 18                                         [horror]
 19                              [animation, comedy]

                                                  Cast
 0   [Josh Hartnett, Ariel Donoghue, Saleka, Alison...
 1   [Nicholas Anscombe, Isabella Colby Browne, Der...
 2   [Annouck Hautbois, Benjamin Bollen, Marie Nonn...
 3   [Ryan Gosling, Emily Blunt, Aaron Taylor-Johns...
 4   [Cailey Fleming, Ryan Reynolds, John Krasinski...
 5   [Madelaine Petsch, Froy Gutierrez, Gabriel Bas...
 6   [Sydney Sweeney, Álvaro Morte, Simona Tabasco,...
 7   [Kim Spearman, Jack Parr, Alexander Arnold, Er...
 8   [Hiftu Quasem, Lauren Lyle, Natalie Mitson, Ni...
 9   [Ryan Reynolds, Josh Brolin, Morena Baccarin, ...
 10  [Megumi Ogata, Hikaru Midorikawa, Toshiyuki Mo...
 11  [Jennifer Lopez, Simu Liu, Sterling K. Brown, ...
 12  [Dakota Fanning, Georgina Campbell, Olwen Foué...
 13  [Lumi Pollack, Emily Bett Rickards, Wayne Char...
 14  [Brie Larson, Teyonah Parris, Iman Vellani, Sa...
 15  [Marlon Brando, Al Pacino, James Caan, Robert ...
 16  [Sigourney Weaver, Carrie Henn, Michael Biehn,...
 17  [Ryu Jun-yeol, Kim Woo-bin, Kim Tae-ri, So Ji-...
 18  [David Dastmalchian, Laura Gordon, Ian Bliss, ...
 19  [Julie Kavner, Dan Castellaneta, Chris Edgerly...  ,
                Movie Titles User Ratings  \
 0                Monkey Man           70
 1                     Tarot           67
 2                15 Cameras           55
 3           Run, Tiger Run!           76
 4           Los de la culpa           71
 5                 No Way Up           64
 6               V de Víctor           80
 7                  Pleasure           62
 8          The Beast Within           57
 9               Unang Tikim           10
 10                    Dange           30
 11           Dune: Part Two           82
 12  Spider-Man: No Way Home           80
 13     John Wick: Chapter 4           77
 14  Avengers: Age of Ultron           73
 15           The First Omen           69
 16       The Age of Adaline           75
 17  The Roundup: No Way Out           73
 18                 Zandalee           43
 19                 Dead Sea           70

                                      Movie Generes  \
 0                               [action, thriller]
 1                                         [horror]
 2                               [horror, thriller]
 3   [animation, adventure, comedy, action, family]
 4                                         [comedy]
 5                       [thriller, horror, action]
 6                                         [comedy]
 7                                          [drama]
 8                        [horror, drama, thriller]
 9                                 [romance, drama]
 10                       [action, drama, thriller]
 11                            [science, adventure]
 12                    [action, adventure, science]
 13                       [action, thriller, crime]
 14                    [action, adventure, science]
 15                                        [horror]
 16                       [romance, fantasy, drama]
 17               [action, crime, comedy, thriller]
 18                      [drama, romance, thriller]
 19                              [thriller, horror]

                                                  Cast
 0   [Dev Patel, Sikandar Kher, Pitobash, Adithi Ka...
 1   [Harriet Slater, Adain Bradley, Avantika, Jaco...
 2   [Will Madden, Angela Wong Carbone, James Babso...
 3   [Nianci Shen, Dawei Liang, Liang Zou, Jianru Z...
 4   [Henry Delgado, Santiago Rendón, Rafael Taibo,...
 5   [Colm Meaney, Phyllis Logan, Sophie McIntosh, ...
 6   [Memo Villegas, Camila Nuñez, Gala Bichir, Adr...
 7   [Sofia Kappel, Zelda Morrison, Tee Reel, Evely...
 8   [Kit Harington, Ashleigh Cummings, James Cosmo...
 9   [Angeli Khang, Robb Guinto, Matthew Francisco,...
 10  [Harshvardhan Rane, Ehan Bhat, TJ Bhanu, Nikit...
 11  [Timothée Chalamet, Zendaya, Rebecca Ferguson,...
 12  [Tom Holland, Zendaya, Benedict Cumberbatch, J...
 13  [Keanu Reeves, Donnie Yen, Bill Skarsgård, Ian...
 14  [Robert Downey Jr., Chris Hemsworth, Mark Ruff...
 15  [Nell Tiger Free, Ralph Ineson, Sônia Braga, B...
 16  [Blake Lively, Michiel Huisman, Harrison Ford,...
 17  [Ma Dong-seok, Lee Jun-hyuk, Munetaka Aoki, Le...
 18  [Nicolas Cage, Erika Anderson, Judge Reinhold,...
 19  [Isabel Gravitt, Alexander Wraith, Dean Camero...  ]

6.b. Combine the data obtained from dataframes in Q6

In [ ]:
# Call the function to get the list of dataframes
dataframes = scrape_movie_and_export()

# Combine all dataframes into a single dataframe
combined_df = pd.concat(dataframes, ignore_index=True)
print(combined_df)

successfully parsed: 200
successfully parsed: 200
successfully parsed: 200
successfully parsed: 200
successfully parsed: 200
               Movie Titles User Ratings  \
0      Deadpool & Wolverine           78
1                  Twisters           71
2              Inside Out 2           76
3           Despicable Me 4           73
4     Bad Boys: Ride or Die           76
..                      ...          ...
95           The First Omen           69
96       The Age of Adaline           75
97  The Roundup: No Way Out           73
98                 Zandalee           43
99                 Dead Sea           70

                             Movie Generes  \
0                [action, comedy, science]
1     [action, adventure, drama, thriller]
2   [animation, family, adventure, comedy]
3      [animation, family, comedy, action]
4        [action, crime, thriller, comedy]
..                                     ...
95                                [horror]
96               [romance, fantasy, drama]
97       [action, crime, comedy, thriller]
98              [drama, romance, thriller]
99                      [thriller, horror]

                                                 Cast
0   [Ryan Reynolds, Hugh Jackman, Emma Corrin, Mat...
1   [Daisy Edgar-Jones, Glen Powell, Anthony Ramos...
2   [Amy Poehler, Maya Hawke, Kensington Tallman, ...
3   [Steve Carell, Kristen Wiig, Will Ferrell, Sof...
4   [Will Smith, Martin Lawrence, Vanessa Hudgens,...
..                                                ...
95  [Nell Tiger Free, Ralph Ineson, Sônia Braga, B...
96  [Blake Lively, Michiel Huisman, Harrison Ford,...
97  [Ma Dong-seok, Lee Jun-hyuk, Munetaka Aoki, Le...
98  [Nicolas Cage, Erika Anderson, Judge Reinhold,...
99  [Isabel Gravitt, Alexander Wraith, Dean Camero...

[100 rows x 4 columns]